# PyTorch实现词嵌入
#### 词嵌入在 pytorch 中非常简单，只需要调用 torch.nn.Embedding(m, n) 就可以了，m 表示单词的总数目，n 表示词嵌入的维度，其实词嵌入就相当于是一个大矩阵，矩阵的每一行表示一个单词

In [1]:
import torch
from torch import nn
from torch.autograd import Variable

In [2]:
embeds = nn.Embedding(2, 5)

In [3]:
embeds.weight

Parameter containing:
tensor([[ 0.6885, -0.9979,  0.3717, -0.2602,  0.5534],
        [ 0.6993, -0.5352,  0.8131, -0.1169, -1.0028]], requires_grad=True)

#### 我们通过 weight 得到了整个词嵌入的矩阵，注意，这个矩阵是一个可以改变的 parameter，在网络的训练中会不断更新，同时词嵌入的数值可以直接进行修改，比如我们可以读入一个预训练好的词嵌入等等

In [5]:
# 直接手动修改词嵌入的值
embeds.weight.data = torch.ones(2, 5)
embeds.weight

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)

#### 如果我们要访问其中一个单词的词向量，我们可以直接调用定义好的词嵌入，但是输入必须传入一个 Variable，且类型是 LongTensor 

In [6]:
index = Variable(torch.LongTensor([1]))
sample = embeds(index)
sample

tensor([[1., 1., 1., 1., 1.]], grad_fn=<EmbeddingBackward>)