In [1]:
# 导入相关的库
import torch
import numpy as np

In [3]:
# 创建一个numpy数组
numpy_array = np.random.randn(4, 5)  # 4-矩阵的行数，5-矩阵的列数，randn-正态分布
numpy_array

array([[-0.70948982,  0.56337342, -0.05890747,  0.0325591 ,  1.8638594 ],
       [-0.08806619,  1.00147051,  1.87643562, -0.5721189 , -0.40294095],
       [-0.00733816,  0.12552496, -0.39004139, -0.28057637,  1.32415578],
       [ 0.00690596,  0.08214539, -1.9701638 ,  0.20036706, -0.18938918]])

# 将numpy数组转换成PyTorch张量（Tensor）有如下两种方式：
# 1、torch.Tensor(numpy_array)
# 2、torch.from_numpy(numpy_array)

In [7]:
torch_tensor1 = torch.Tensor(numpy_array)
torch_tensor2 = torch.from_numpy(numpy_array)
print(torch_tensor1)
print(torch_tensor2)
# 使用以上两种方法进行转换的时候，会直接将numpy array的数据类型转换为对应的PyTorch Tensor类型

tensor([[-0.7095,  0.5634, -0.0589,  0.0326,  1.8639],
        [-0.0881,  1.0015,  1.8764, -0.5721, -0.4029],
        [-0.0073,  0.1255, -0.3900, -0.2806,  1.3242],
        [ 0.0069,  0.0821, -1.9702,  0.2004, -0.1894]])
tensor([[-0.7095,  0.5634, -0.0589,  0.0326,  1.8639],
        [-0.0881,  1.0015,  1.8764, -0.5721, -0.4029],
        [-0.0073,  0.1255, -0.3900, -0.2806,  1.3242],
        [ 0.0069,  0.0821, -1.9702,  0.2004, -0.1894]], dtype=torch.float64)


# 也可以使用以下方法将PyTorch Tensor转换为numpy array:
# tensor.numpy()

In [10]:
numpy_array1 = torch_tensor1.numpy()
numpy_array1

array([[-0.7094898 ,  0.56337345, -0.05890747,  0.0325591 ,  1.8638594 ],
       [-0.08806619,  1.0014706 ,  1.8764356 , -0.5721189 , -0.40294096],
       [-0.00733816,  0.12552495, -0.39004138, -0.28057638,  1.3241558 ],
       [ 0.00690596,  0.08214539, -1.9701638 ,  0.20036706, -0.18938917]],
      dtype=float32)

# 访问Tensor的一些属性：大小、数据类型、维度和元素个数

In [11]:
# 1、大小
print(torch_tensor1.shape)
print(torch_tensor1.size())

torch.Size([4, 5])
torch.Size([4, 5])


In [12]:
# 2、数据类型
print(torch_tensor1.type())

torch.FloatTensor


In [13]:
# 3、维度
print(torch_tensor1.dim())

2


In [14]:
# 4、所有的元素个数
print(torch_tensor1.numel())

20


In [15]:
# 练习：创建一个 float64、大小是 3 x 2、随机初始化的 tensor，将其转化为 numpy 的 ndarray，输出其数据类型
x = torch.randn(3, 2)  # torch.randn(row, col) -> 生成一个row x col的随机张量，默认的数据类型是torch.FloatTensor
print(x)
x = x.type(torch.DoubleTensor)
x = x.numpy()
print(x.dtype)
# tensor的数据类型与numpy array的数据类型的对应关系如下：
# tensor数据类型      <-->     numpy array数据类型
# torch.FloatTensor   <-->     float32
# torch.DoubleTensor  <-->     float64

tensor([[ 0.4728, -0.6310],
        [ 0.2921,  1.4038],
        [-0.1672,  1.0638]])
float64


# Tensor的一些操作

In [16]:
x = torch.ones(2, 2)
print(x)
# 使用torch内置的函数生成的tensor的数据类型都是torch.FloatTensor

tensor([[1., 1.],
        [1., 1.]])


In [17]:
print(x.type())

torch.FloatTensor


In [18]:
# 将其转换为整型
x = x.type(torch.LongTensor)
print(x)
print(x.type())

tensor([[1, 1],
        [1, 1]])
torch.LongTensor


In [19]:
# 生成服从正态分布的随机矩阵（张量）
x = torch.randn(4, 3)
print(x)

tensor([[-0.5318,  0.8764, -0.3508],
        [ 1.1702, -1.1039,  0.6730],
        [-0.2964,  0.9932,  0.9772],
        [ 1.3673, -0.9330,  0.3974]])


In [20]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)  # 获得x每一行最大值组成的tensor以及最大值对应的下标组成的tensor
print(max_value)
# dim=1代表行，dim=0代表列

tensor([0.8764, 1.1702, 0.9932, 1.3673])


In [21]:
print(max_idx)

tensor([1, 0, 1, 0])


In [22]:
# 沿着行对x求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([-0.0062,  0.7393,  1.6739,  0.8317])


In [23]:
# 增加维度/减少维度
print(x.size())
x = x.unsqueeze(0)  # 在第一维增加，默认增加的维度值为1
print(x.size())

torch.Size([4, 3])
torch.Size([1, 4, 3])


In [28]:
x = x.unsqueeze(1)  # 在第二维增加
print(x.size())

torch.Size([1, 1, 4, 3])


In [29]:
x = x.squeeze(0)  # 减少第一维
print(x.size())

torch.Size([1, 4, 3])


In [30]:
x = x.unsqueeze(0)
print(x.size())
x = x.squeeze()  # 如果不指定减少的维度，那么就将维度为1的全部去掉
print(x.size())

torch.Size([1, 1, 4, 3])
torch.Size([4, 3])


In [31]:
# 重新排列tensor的维度
x = torch.randn(3, 4, 5)  # torch.randn(page, row, col)表示生成page个/页的row x col的矩阵
print(x)
print(x.size())

# 1、permute可以重新排列tensor的维度
x = x.permute(1, 0, 2)
print(x)
print(x.size())

# 2、transpose可以交换tensor中的两个维度
x = x.transpose(0, 2)
print(x)
print(x.size())

tensor([[[-0.5228, -0.2066,  1.2517, -0.0956, -0.9913],
         [ 0.5939, -0.3745,  0.6761, -0.7169,  0.0699],
         [-0.1086, -0.2869,  1.4100,  0.9021,  1.4485],
         [-0.6650, -1.2225, -1.4078,  0.4694,  0.0691]],

        [[ 0.0381,  0.0493, -0.0357,  1.3380,  2.0331],
         [ 0.9673,  0.5728, -1.5369,  0.3273, -0.0182],
         [-0.5132, -0.1296,  0.9601,  0.6430,  0.3313],
         [ 0.5773,  1.0815,  0.8792, -0.4347,  0.0882]],

        [[ 0.4812, -0.8915,  1.3252, -0.9487, -0.3288],
         [ 0.3955, -1.6038, -0.5757,  0.1552, -0.7201],
         [ 0.6502,  0.5975,  1.2848, -0.3548,  0.4127],
         [ 1.5145, -1.4020, -0.0115,  0.2202,  1.1712]]])
torch.Size([3, 4, 5])
tensor([[[-0.5228, -0.2066,  1.2517, -0.0956, -0.9913],
         [ 0.0381,  0.0493, -0.0357,  1.3380,  2.0331],
         [ 0.4812, -0.8915,  1.3252, -0.9487, -0.3288]],

        [[ 0.5939, -0.3745,  0.6761, -0.7169,  0.0699],
         [ 0.9673,  0.5728, -1.5369,  0.3273, -0.0182],
         [ 0.3955,

In [32]:
# 使用view对tensor进行reshape
x = torch.randn(3, 4, 5)
print(x)
print(x.size())

x = x.view(-1, 5)  # -1表示任意维度，但是是确定的，因为可以由其他维度推断出来，比如在这个
                   # 例子中，x总共有60个元素，现在其中一个维度等于5，那么另一个维度就等于12
print(x)
print(x.size())

x = x.view(3, 20)
print(x)
print(x.size())

tensor([[[-0.5659, -0.7582, -1.6545, -0.1380, -1.3386],
         [-0.9407, -1.6829,  0.5473,  0.4574, -1.5802],
         [-0.1080, -1.9968,  0.0184, -0.7080,  0.1897],
         [-0.5889,  0.3203,  1.5985, -0.6179, -0.0100]],

        [[ 0.2436,  0.5331, -1.1293, -2.9650, -1.3455],
         [-0.4011, -0.1047,  0.0612, -0.8886,  0.3830],
         [ 0.6025, -0.5958, -0.7919, -1.3748, -0.9960],
         [-1.2596,  0.8188,  0.8267, -1.3869,  0.9227]],

        [[ 1.0257, -1.5440, -1.3266, -1.2812,  2.9005],
         [-0.4314, -1.6084, -1.5119, -0.5062,  1.0769],
         [ 1.1831, -0.7531, -0.1329,  0.2261, -0.6193],
         [ 0.4415, -0.1536,  0.1104, -0.0824,  1.1667]]])
torch.Size([3, 4, 5])
tensor([[-0.5659, -0.7582, -1.6545, -0.1380, -1.3386],
        [-0.9407, -1.6829,  0.5473,  0.4574, -1.5802],
        [-0.1080, -1.9968,  0.0184, -0.7080,  0.1897],
        [-0.5889,  0.3203,  1.5985, -0.6179, -0.0100],
        [ 0.2436,  0.5331, -1.1293, -2.9650, -1.3455],
        [-0.4011, -0.1047

In [33]:
# torch的加法与inplace操作
# 1、加法
x = torch.randn(3, 4)
y = torch.randn(3, 4)

z = x + y
print(z)

z = torch.add(x, y)
print(z)

tensor([[-1.4799,  0.2519, -0.0413, -0.9004],
        [ 1.5527,  1.4856,  0.6605, -3.1807],
        [-2.0206, -3.2847,  1.1356,  0.4825]])
tensor([[-1.4799,  0.2519, -0.0413, -0.9004],
        [ 1.5527,  1.4856,  0.6605, -3.1807],
        [-2.0206, -3.2847,  1.1356,  0.4825]])


In [34]:
# 2、inplace操作是直接对tensor进行操作而不需要另外开辟内存空间，一般是直接在操作符的后面加_
x.add_(y)  # 相当于x = x + y
print(x)

tensor([[-1.4799,  0.2519, -0.0413, -0.9004],
        [ 1.5527,  1.4856,  0.6605, -3.1807],
        [-2.0206, -3.2847,  1.1356,  0.4825]])


# 变量（Variable）
## tensor 是 PyTorch 中的完美组件，但是构建神经网络还远远不够，我们需要能够构建计算图的 tensor，这就是 Variable。Variable 是对 tensor 的封装，操作和 tensor 是一样的，但是每个 Variabel都有三个属性:
## 1、.data：变量的值，是一个tensor
## 2、.grad：变量的梯度，是一个tensor
## 3、.grad_fn：反映这个Variable是如何得到的

In [35]:
# 导入Variable
from torch.autograd import Variable

In [36]:
x_tensor = torch.randn(10, 5)
y_tensor = torch.randn(10, 5)

# 将tensor转换为Variable
x = Variable(x_tensor, requires_grad=True)  # 默认Variable是不求梯度的，所以我们用这种方
                                            # 式申明需要求梯度。
y = Variable(y_tensor, requires_grad=True)

In [37]:
z = torch.sum(x + y)

In [38]:
print(z.data)
print(z.grad_fn)

tensor(-6.2925)


In [40]:
# 求x和y的梯度
z.backward()

print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


# 练习：
### 尝试构建一个函数$y=x^2$，然后求$x=2$的导数

In [43]:
x = Variable(torch.FloatTensor([2]), requires_grad=True)
y = x ** 2

y.backward()
print(x.grad)

tensor([4.])
