In [1]:
import torch
from torch.autograd import Variable

## 简单情况的自动求导

In [2]:
x = Variable(torch.FloatTensor([2]), requires_grad=True)
y = x + 2
z = y ** 2 + 3
print(z)

tensor([19.], grad_fn=<AddBackward0>)


In [3]:
# 求对x的导数
z.backward()
print(x.grad)

tensor([8.])


## 复杂情况的自动求导

In [4]:
x = Variable(torch.randn(10, 20), requires_grad=True)
y = Variable(torch.randn(10, 5), requires_grad=True)
w = Variable(torch.randn(20, 5), requires_grad=True)

out = torch.mean(y - torch.matmul(x, w))
print(out)
# torch.mean()：求整个tensor的均值
# torch.matmul(A, B)：矩阵乘法：A x B

tensor(0.6134, grad_fn=<MeanBackward0>)


In [5]:
out.backward()
print(x.grad)

tensor([[-0.0031, -0.0025,  0.0180, -0.0421,  0.0775,  0.0173,  0.0959, -0.0819,
         -0.0808,  0.0176, -0.0060,  0.0045,  0.0164,  0.0288,  0.0493, -0.0328,
          0.0390,  0.0009, -0.0534,  0.0088],
        [-0.0031, -0.0025,  0.0180, -0.0421,  0.0775,  0.0173,  0.0959, -0.0819,
         -0.0808,  0.0176, -0.0060,  0.0045,  0.0164,  0.0288,  0.0493, -0.0328,
          0.0390,  0.0009, -0.0534,  0.0088],
        [-0.0031, -0.0025,  0.0180, -0.0421,  0.0775,  0.0173,  0.0959, -0.0819,
         -0.0808,  0.0176, -0.0060,  0.0045,  0.0164,  0.0288,  0.0493, -0.0328,
          0.0390,  0.0009, -0.0534,  0.0088],
        [-0.0031, -0.0025,  0.0180, -0.0421,  0.0775,  0.0173,  0.0959, -0.0819,
         -0.0808,  0.0176, -0.0060,  0.0045,  0.0164,  0.0288,  0.0493, -0.0328,
          0.0390,  0.0009, -0.0534,  0.0088],
        [-0.0031, -0.0025,  0.0180, -0.0421,  0.0775,  0.0173,  0.0959, -0.0819,
         -0.0808,  0.0176, -0.0060,  0.0045,  0.0164,  0.0288,  0.0493, -0.0328,
      

In [7]:
print(y.grad)

tensor([[0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200]])


In [8]:
print(w.grad)

tensor([[-0.0601, -0.0601, -0.0601, -0.0601, -0.0601],
        [-0.0401, -0.0401, -0.0401, -0.0401, -0.0401],
        [-0.0942, -0.0942, -0.0942, -0.0942, -0.0942],
        [-0.0255, -0.0255, -0.0255, -0.0255, -0.0255],
        [-0.0024, -0.0024, -0.0024, -0.0024, -0.0024],
        [ 0.0261,  0.0261,  0.0261,  0.0261,  0.0261],
        [ 0.0312,  0.0312,  0.0312,  0.0312,  0.0312],
        [-0.0440, -0.0440, -0.0440, -0.0440, -0.0440],
        [ 0.0272,  0.0272,  0.0272,  0.0272,  0.0272],
        [ 0.0009,  0.0009,  0.0009,  0.0009,  0.0009],
        [ 0.0217,  0.0217,  0.0217,  0.0217,  0.0217],
        [ 0.0332,  0.0332,  0.0332,  0.0332,  0.0332],
        [ 0.0184,  0.0184,  0.0184,  0.0184,  0.0184],
        [-0.0171, -0.0171, -0.0171, -0.0171, -0.0171],
        [-0.1415, -0.1415, -0.1415, -0.1415, -0.1415],
        [-0.0035, -0.0035, -0.0035, -0.0035, -0.0035],
        [-0.0308, -0.0308, -0.0308, -0.0308, -0.0308],
        [-0.0667, -0.0667, -0.0667, -0.0667, -0.0667],
        [ 

In [9]:
m = Variable(torch.FloatTensor([[2, 3]]), requires_grad=True)
n = Variable(torch.zeros(1, 2))

print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [10]:
n[0, 0] = m[0, 0] ** 2
n[0, 1] = m[0, 1] ** 3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


### 将上面写成公式为：$n=(n_0, n_1)=(m_0^2, m_1^3)$
### 那么n对m的导数为：$\frac{\partial n}{\partial m}=(\frac{\partial n}{\partial m_0},\frac{\partial n}{\partial m_1})$
## 在 PyTorch 中，如果要调用自动求导，需要往backward()中传入一个参数，这个参数的形状和 n 一样大，比如是$(w_0,w_1)$
## 其中，$\frac{\partial n}{\partial m_0}=w_0\frac{\partial n_0}{\partial m_0}+ w_1\frac{\partial n_1}{\partial m_0}$
## $\frac{\partial n}{\partial m_1}=w_0\frac{\partial n_0}{\partial m_1}+ w_1\frac{\partial n_1}{\partial m_1}$

In [11]:
n.backward(torch.ones_like(n))  # 将(w0, w1)规定为(1, 1)
print(m.grad)
# torch.ones_like(n)：生成一个大小和n一样的、值全为1的tensor

tensor([[ 4., 27.]])


## 多次自动求导
### 通过调用 backward 我们可以进行一次自动求导，如果我们再调用一次 backward，会发现程序报错，没有办法再做一次。这是因为 PyTorch 默认做完一次自动求导之后，计算图就被丢弃了，所以两次自动求导需要手动设置一个东西，我们通过下面的小例子来说明。

In [12]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)
y = x * 2 + x ** 2 + 3
print(y)

tensor([18.], grad_fn=<AddBackward0>)


In [13]:
y.backward(retain_graph=True)  # 通过设置retain_graph为True来保留计算图

In [14]:
print(x.grad)

tensor([8.])


In [15]:
y.backward()

In [16]:
print(x.grad)

tensor([16.])
